FROM i386/ubuntu:20.04 AS BUILD32
ENV build_cores 10
ARG http_proxy
ENV http_proxy=${http_proxy}
ENV https_proxy=${http_proxy}

RUN sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install git ccache -y \
    && apt-get build-dep wine -y \
    && apt-get build-dep wine-development -y \
    && /usr/sbin/update-ccache-symlinks

COPY container-scripts/build32.sh build32.sh

RUN chmod +x build32.sh

RUN mkdir /build

VOLUME [ "/build" ]
